# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: fragments_project
  pool: 5
  username: postgres  
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: fragments_project
  pool: 5
  username: postgres  
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: fragments_project
  pool: 5
  username: postgres  
  password: postgres
  host: localhost